language: bash
sudo: required

# Some initial setup
before_install:
- sudo apt-get update
- sudo apt-get install -y socat util-linux
- sudo docker build -t ubuntu-util-linux:1 util-linux/
- sudo docker run --rm -v $(pwd):/tmp/files ubuntu-util-linux:1 /bin/sh -c "cp -fv /util-linux/nsenter /tmp/files/"
- sudo mv -fv nsenter /usr/local/bin/

script: sudo bash test.sh
