language: bash
sudo: required

# Some initial setup
before_install:
- sudo apt-get update
- sudo apt-get install -y socat util-linux

# Get the needed nsenter tool for Ubuntu 14.04 (current tarvisCI build VM version)
- sudo docker run --rm -v $(pwd):/target jpetazzo/nsenter
- sudo mv -fv nsenter /usr/local/bin/

script:
- sudo bash test.sh
